// NOTE: The 'mapping.json' file is generated by the build process and it
// should not be edited manually. This file is tracked by the VCS.
export { default as glyphCodepointsMapping } from "./mapping.json" assert { type: "json" };
